### ISSUE TITLE
[Scan Encrypted Content] Include in the parameters sent to the content scanner the `mimetype` extracted from the content.info.

### ISSUE THREAD

**Issue by giomfo** [matrix-org/matrix-ios-sdk#1186]
Hi, a recent change in the attachment description at the Element client level broke the use of the content scanner in encrypted rooms.
Indeed the `mimetype` field has been removed from the content.file description (because it was already mentioned in the content.info). See the related PR in iOS is https://github.com/matrix-org/matrix-ios-sdk/pull/1125

The problem is the [matrix-content-scanner](https://github.com/matrix-org/matrix-content-scanner) blocks all the encrypted contents when the filter on mimetype is enabled. Indeed the content scanner is looking for the mimetype in the content.file description provided by the client.

To make ios client compatible with the current version of the content scanner, we decided to update the parameters sent to the scanner by including the `mimetype` extracted from the content.info.

**Comment by giomfo** [comment]
the change may take place in these 2 places:
- https://github.com/matrix-org/matrix-ios-sdk/blob/6405878fca79416f024aa8f5f5068e3423778c5f/MatrixSDK/ContentScan/MXScanManager.m#L524
- https://github.com/matrix-org/matrix-ios-sdk/blob/1b3e50853022beb0836dc404215f03c47bf64d3b/MatrixSDK/Utils/Media/MXMediaManager.m#L675

**Comment by ShadowJonathan** [comment]
......why would you want to leak additional metadata in an encrypted room?

To me, the removal of mimetype in encrypted rooms sounds like a good thing, reverting it should be a security concern.

Also, what use would it have for encrypted rooms? What would content scanners be able to find in encrypted data?

If content scanners hiccup because the media metadata it's scanning for doesn't have a mimetype, then that's the fault of the content scanner to hiccup on that, and/or the fault on the server for allowing to leave out that field (if it's required by the spec)

To me this issue sounds pointless and anti-privacy for no concrete reason.

**Comment by ShadowJonathan** [comment]
Also, I just saw https://github.com/matrix-org/matrix-doc/pull/2582, which explicitly mentions https://github.com/matrix-org/matrix-ios-sdk/pull/1125 as it’s implementation, so this change is here to stay.

This issue should be close, and the actual problem solved at the content scanner repo. (CC @stefanceriu)

**Comment by giomfo** [comment]
@ShadowJonathan hi, FYI we decided to cancel this change request.
The actual problem will be solved at the content scanner repo
