### ISSUE TITLE
Content prefix path.

### ISSUE THREAD

**Issue by VictorLiubchenko** [matrix-org/matrix-ios-sdk#213]
When my home server something like this https://foo.org/something, and I want upload image, your method provide me path like "/_matrix/media/v1".

In MXHTTPClient try request method 
    NSString *URLString = [[NSURL URLWithString:path relativeToURL:httpManager.baseURL] absoluteString];

path start with /_matrix/media/v1.... and base url look like https://foo.org/something/ and we have result as https://foo.org/_matrix/media/v1.... (http://nshipster.com/nsurl/)

### Could you make kMXContentPrefixPath changeable or properties?

**Comment by giomfo** [comment]
@VictorLiubchenko thanks for your remark.

I prepared a change in MXHTTPClient try request method in order to handle correctly the homeserver whose the url is a subdirectory (and not a root). My change is waiting for reviewing.

Why did you report this issue only for the image uploading? It should impact all your requests, no?

**Comment by VictorLiubchenko** [comment]
Thanks for the quick answer)

MXRestClient has property "apiPathPrefix", it help in other case. For example 
set apiPathPrefix = /something/_matrix/client/r0, and

"https://foo.org/something/" after added path "/something/_matrix/client/r0" looks like "https://foo.org/something/_matrix/client/r0".

**Comment by giomfo** [comment]
@VictorLiubchenko fixed in develop branch
