### ISSUE TITLE
macOS port

### ISSUE THREAD

**Issue by aapierce0** [matrix-org/matrix-ios-sdk#216]
I'm interested in building a true native macOS client. Is there any reason this framework couldn't (or shouldn't) include a macOS build target?

I'm currently looking into adding it myself. A lot of the work appears to be replacing the `UI*` classes with their `NS*` counterparts, like so:

    #if TARGET_OS_IPHONE
        UIImage* foo;
    #elif TARGET_OS_OSX
        NSImage* foo;
    #endif 

... and then `#import <Cocoa/Cocoa.h>` instead of `<UIKit/UIKit.h>` when the platform is macOS

I notice that the [OLMKit](https://matrix.org/git/olm/about/) pod currently doesn't support macOS, but after a very brief (10 min) skim through that project, it looks like that would be portable to macOS as well. However, since it's hosted on matrix.org instead of github, I'm not sure what the protocol is for contributing.

**Comment by ara4n** [comment]
It would be absolutely awesome to have a true native macOS client.  matrix-ios-sdk itself is a relatively low level library that wraps and manages the Matrix HTTP API itself, and can probably be made to build for macOS very easily indeed.  However, all the UI stuff (e.g. UIImage and friends) lives in matrix-ios-kit (MatrixKit), which I think is more where the porting work would need to happen.

Many bits of MatrixKit probably can be made to support both targets, but there's going to be some higher level layers which will probably need entirely separate macOS variants rather than using `#ifdefs`.  For instance, I suspect you'd need to build a separate tree of XIBs for macOS in addition to the current iOS ones, and of course the storyboard of the app itself will need to be different.

My suggestion (beware: i've not actually hacked on matrix-ios-kit and matrix-ios-sdk that much and am a bit rusty on iOS dev) would be to fork matrix-ios-sdk and matrix-ios-kit on Github, take the MatrixKitSample app (https://github.com/matrix-org/matrix-ios-kit/tree/develop/Samples/MatrixKitSample), and try working your way through, adding in ifdefs, as well as 'forking' the XIBs & Storyboards to support macOS.  Perhaps you may not need to fork any actual controllers themselves.

In terms of OLMKit: libolm itself builds on OSX, although the Makefile requires minimal tweaking; i currently have:

```
diff --git a/Makefile b/Makefile
index 438fa68..db0e701 100644
--- a/Makefile
+++ b/Makefile
@@ -15,8 +15,8 @@ EMCC = emcc
 AFL_CC = afl-gcc
 AFL_CXX = afl-g++
 
-RELEASE_TARGET := $(BUILD_DIR)/libolm.so.$(VERSION)
-DEBUG_TARGET := $(BUILD_DIR)/libolm_debug.so.$(VERSION)
+RELEASE_TARGET := $(BUILD_DIR)/libolm.dylib.$(VERSION)
+DEBUG_TARGET := $(BUILD_DIR)/libolm_debug.dylib.$(VERSION)
 JS_TARGET := javascript/olm.js
 
 JS_EXPORTED_FUNCTIONS := javascript/exported_functions.json
@@ -107,10 +107,8 @@ lib: $(RELEASE_TARGET)
 
 $(RELEASE_TARGET): $(RELEASE_OBJECTS)
        $(CXX) $(LDFLAGS) --shared -fPIC \
-            -Wl,-soname,libolm.so.$(MAJOR) \
-            -Wl,--version-script,version_script.ver \
             $(OUTPUT_OPTION) $(RELEASE_OBJECTS)
-       ln -sf libolm.so.$(VERSION) $(BUILD_DIR)/libolm.so.$(MAJOR)
+       ln -sf libolm.dylib.$(VERSION) $(BUILD_DIR)/libolm.dylib.$(MAJOR)
 
 debug: $(DEBUG_TARGET)
 .PHONY: debug
```

...although obviously that should be built into the Makefile itself.  I know of no reason why OLMKit itself couldn't be made to trivially build on macOS.  The reason it sits on matrix.org/git rather than github is purely legal (the code has been written by folks in the UK & France, and we don't want to have to jump through cryptography re-export hoops by importing it to Github in the US, and thus be responsible when folks then export it out of the US again by downloading it from Github.  matrix.org/git is hosted in the UK & Holland, so we sidestep having to worry about US export compliance).

**Comment by ara4n** [comment]
@aapierce0 out of interest, are you getting anywhere with a macOS client? someone else was asking about this just now in Matrix HQ

**Comment by aapierce0** [comment]
I have something that connects to a home server, but I wouldn't recommend anyone use it. Right now, it's only able to authenticate a user with a username/password, show them the rooms they're already part of, and allow them to chat (text only) in those rooms.

https://github.com/aapierce0/MatrixClient

**Comment by ara4n** [comment]
Ooh, this looks incredibly promising :D let us know if there's any way we can help :)
