### ISSUE TITLE
iOS Calling UI

### ISSUE THREAD

**Issue by anuj-gola** [matrix-org/matrix-ios-sdk#441]
I used Matrix for voice and video calling. It show push notification as a call is arrived to iOS device but doest not show the calling UI on the device if app is in background OR killed. Is there a way I can show normal calling UI as call comes to the device. I need to match WhatsApp calling on iOS for our app. I searched a little bit and found that it can be achieved by iOS native framework "CallKit" but we don't have "CallKit" in our app. Is there a way we can achieve this functionality using Matrix SDK.

If we need to add "CallKit" to our app, is there a way I can direct Matrix SDK to use "CallKit" framework and not to use Push notifications.

**Comment by anuj-gola** [comment]
Guys, is there any update regarding the mentioned issue?

**Comment by anuj-gola** [comment]
Guys, please consider this on high priority and let us know the update.

**Comment by manuroe** [comment]
CallKit must be managed at the application level. This SDK can be used for a MacOS app.
Riot uses CallKit since version [0.6.0](https://github.com/vector-im/riot-ios/releases/tag/v0.6.0).
More specifically, you can look at all PRs in Riot related to callkit. There are not too much (https://github.com/vector-im/riot-ios/pulls?q=is%3Apr+callkit+is%3Aclosed).
