### ISSUE TITLE
Matrix Swift Build Error

### ISSUE THREAD

**Issue by expertalex** [matrix-org/matrix-ios-sdk#457]
When adding Matrix Swift to Swift Project I see **76 Swift Compiler Errors** in MXRoom, MXRestClient and MXSession classes extensions:

Cannot convert call result type '(_) -> Void' to expected type '(() -> Void)!'

Cannot convert call result type '(_) -> Void' to expected type 'MXOnBackgroundSyncDone!' (aka 'ImplicitlyUnwrappedOptional<() -> ()>')

For Example this code:

```Swift
    /**
     Set the topic of the room.
     
     - parameters:
        - topic: the topic to set.
        - completion: A block object called when the operation completes.
        - response: Indicates whether the operation was a success or failure.
     
     - returns: a `MXHTTPOperation` instance.
     */
    @nonobjc @discardableResult func setTopic(_ topic: String, completion: @escaping (_ response: MXResponse<Void>) -> Void) -> MXHTTPOperation {
        return __setTopic(topic, success: currySuccess(completion), failure: curryFailure(completion))
    }
```
Has the following error:

> Cannot convert call result type '(_) -> Void' to expected type '(() -> Void)!' 

Why is this happened?

Swift Version 4
Matrix Pods:
	# ---------------------------------------------
	# Matrix SDK
	# ---------------------------------------------
	pod 'SwiftMatrixSDK'
	# Enable VoIP
	pod 'MatrixSDK/JingleCallStack'

**Comment by manuroe** [comment]
Swift 4 has broken SwiftMatrixSDK.

This swift layer was brought by the community. The matrix core team runs projects in Obj-C so that maintaining this pod is not in our priorities at the moment.

What I can suggest:
- downgrade your project to Swift 3. You can achieve this with CocoaPods by adding a `.swift-version` file next to your Podfile. This text file contains only the string `3.2`.
- or use directly the Obj-C pod, `pod MatrixSDK`,  and skip the Swift refinement layer of SwiftMatrixSDK
- or try to fix these errors. A PR from the community will be warmly welcomed

**Comment by johnflanagan-spok** [comment]
There's more discussion about this on issue #393

**Comment by manuroe** [comment]
@expertalex, before @johnflanagan-spok's fix appears in an official pod release, you can point to the develop branch of the pod, ie:
```
pod 'SwiftMatrixSDK', :git => 'https://github.com/matrix-org/matrix-ios-sdk.git', :branch => 'develop'
```
