### ISSUE TITLE
Why using Archive to store room messages instead of DB?

### ISSUE THREAD

**Issue by PatrickLi1107** [matrix-org/matrix-ios-sdk#709]

**Comment by manuroe** [comment]
The reason is historical.
Before the introduction of the Lazy Loading of room members in the Matrix protocol last year , serialising data to files was the only way to have a working app.

Without that feature, you get all members events of all rooms at the initial sync. This can represent hundreds of thousands of entities. No DB can handle and write such amount of data in a reasonable amount of time.

FTR, the rewrite of Riot-Android, RiotX, uses realm.io with Lazy Loading and it works.
We consider to improve the iOS SDK but we do not know when yet.
