### ISSUE TITLE
MXRoom.unreadEvents and [MXStore unreadEvents::] should be removed

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-ios-sdk#82]
because they can lie since v2 /sync and the potential gaps in received messages.

It should be replaced by 'unreadEventsCount' which is the most relevant information for an app.
This count should be provided by the homeserver but it is not available yet.

**Comment by giomfo** [comment]
But it is not so easy for the server to compute the right unread count
because the server does not know which kind/type of events the client actually considers.
The server can only return the number of unread events whatever their type, whereas the client displays only a subset of these events (ignore some membership event for example)

We will limit this information to a boolean value: has unread or not.
